import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import { Navbar } from "@/components/navbar";
import { cn } from "@/lib/utils";
import { Footer } from "@/components/footer";

const Helvetica = localFont({
  src: [
    {
      path: "/fonts/HelveticaNeue.woff2",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("bg-[#F0EFEC]", Helvetica.className)}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
